SIZE_1M = 0x100000
SIZE_1K = 1024


class MemoryMap:
    _no_prefix = ["CONFIG_SYS_TEXT_BASE"]

    DRAM_BASE = 0x80000000
    DRAM_SIZE = 256 * SIZE_1M

    FREERTOS_SIZE = 2 * SIZE_1M
    FREERTOS_ADDR = DRAM_BASE + DRAM_SIZE - FREERTOS_SIZE
    FSBL_C906L_START_ADDR = FREERTOS_ADDR

    MONITOR_ADDR = DRAM_BASE
    ATF_SIZE = 512 * SIZE_1K
    OPENSBI_SIZE = 512 * SIZE_1K
    OPENSBI_FDT_ADDR = MONITOR_ADDR + OPENSBI_SIZE

    KERNEL_MEMORY_ADDR = DRAM_BASE
    KERNEL_MEMORY_SIZE = DRAM_SIZE - FREERTOS_SIZE

    ION_SIZE = 0
    H26X_BITSTREAM_SIZE = 0
    H26X_ENC_BUFF_SIZE = 0
    ISP_MEM_BASE_SIZE = 0
    FREERTOS_RESERVED_ION_SIZE = 0

    ION_ADDR = FREERTOS_ADDR - ION_SIZE
    H26X_BITSTREAM_ADDR = ION_ADDR
    H26X_ENC_BUFF_ADDR = H26X_BITSTREAM_ADDR + H26X_BITSTREAM_SIZE
    ISP_MEM_BASE_ADDR = H26X_ENC_BUFF_ADDR + H26X_ENC_BUFF_SIZE

    BOOTLOGO_SIZE = 8000 * SIZE_1K
    BOOTLOGO_ADDR = ION_ADDR - BOOTLOGO_SIZE
    FRAMEBUFFER_SIZE = BOOTLOGO_SIZE
    FRAMEBUFFER_ADDR = BOOTLOGO_ADDR

    CVI_UPDATE_HEADER_SIZE = SIZE_1K
    UIMAG_SIZE = 16 * SIZE_1M
    UIMAG_ADDR = DRAM_BASE + 24 * SIZE_1M
    CVI_UPDATE_HEADER_ADDR = UIMAG_ADDR - CVI_UPDATE_HEADER_SIZE
    FSBL_UNZIP_ADDR = UIMAG_ADDR
    FSBL_UNZIP_SIZE = UIMAG_SIZE

    CONFIG_SYS_TEXT_BASE = DRAM_BASE + 2 * SIZE_1M
    CONFIG_SYS_INIT_SP_ADDR = UIMAG_ADDR + UIMAG_SIZE
